create table if not exists permission (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    description varchar(255) default null,
    CONSTRAINT permissions_pkey PRIMARY KEY (id)
);