create table if not exists users (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_name varchar(255) unique default null,
    name varchar(255) default null,
    password varchar(255) default null,
    account_non_expired bool default null,
    account_non_locked bool default null,
    credentials_non_expired bool default null,
    enabled bool default null,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);